In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DataSet/news_dataset.csv')

In [4]:
df.head()

label                                               text
0  REAL  Payal has accused filmmaker Anurag Kashyap of ...
1  FAKE  A four-minute-long video of a woman criticisin...
2  FAKE  Republic Poll, a fake Twitter account imitatin...
3  REAL  Delhi teen finds place on UN green list, turns...
4  REAL  Delhi: A high-level meeting underway at reside...

In [5]:
df.isnull().sum()

label    0
text     8
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.duplicated().sum()

np.int64(1492)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [10]:
import re
def Get_words(df):
  df['text'] = df['text'].str.lower()
  df['text'] = df['text'].str.replace(r'[^a-zA-Z\s]', '', regex=True)
  return df

In [11]:
df=Get_words(df)

In [12]:
df['Tokens'] = df['text'].str.split()

In [13]:
df['Len_token_stopwords'] = df['Tokens'].apply(lambda x: len(x))

In [14]:
from nltk.corpus import stopwords
nltk.download('stopwords')
df['token_not_stopwords'] = df['Tokens'].apply(lambda x: [word for word in x if word not in stopwords.words('english')])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
df['Len_token_not_stopwords'] = df['token_not_stopwords'].apply(lambda x: len(x))

In [16]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
df['stemming'] = df['token_not_stopwords'].apply(lambda x: [ps.stem(word) for word in x])

In [17]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
df['lemmatization'] = df['token_not_stopwords'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [18]:
df.head()

label                                               text  \
0  REAL  payal has accused filmmaker anurag kashyap of ...   
1  FAKE  a fourminutelong video of a woman criticising ...   
2  FAKE  republic poll a fake twitter account imitating...   
3  REAL  delhi teen finds place on un green list turns ...   
4  REAL  delhi a highlevel meeting underway at residenc...   

                                              Tokens  Len_token_stopwords  \
0  [payal, has, accused, filmmaker, anurag, kashy...                   97   
1  [a, fourminutelong, video, of, a, woman, criti...                  564   
2  [republic, poll, a, fake, twitter, account, im...                  464   
3  [delhi, teen, finds, place, on, un, green, lis...                  376   
4  [delhi, a, highlevel, meeting, underway, at, r...                  882   

                                 token_not_stopwords  Len_token_not_stopwords  \
0  [payal, accused, filmmaker, anurag, kashyap, b...                       51   
1  [fourminutelong, video, woman, criticising, go...                      302   
2  [republic, poll, fake, twitter, account, imita...                      275   
3  [delhi, teen, finds, place, un, green, list, t...                      236   
4  [delhi, highlevel, meeting, underway, residenc...                      518   

                                            stemming  \
0  [payal, accus, filmmak, anurag, kashyap, behav...   
1  [fourminutelong, video, woman, criticis, gover...   
2  [republ, poll, fake, twitter, account, imit, a...   
3  [delhi, teen, find, place, un, green, list, tu...   
4  [delhi, highlevel, meet, underway, resid, rajy...   

                                       lemmatization  
0  [payal, accused, filmmaker, anurag, kashyap, b...  
1  [fourminutelong, video, woman, criticising, go...  
2  [republic, poll, fake, twitter, account, imita...  
3  [delhi, teen, find, place, un, green, list, tu...  
4  [delhi, highlevel, meeting, underway, residenc...

In [19]:
df['sent_lemmatization'] = df['lemmatization'].apply(lambda x: ' '.join(x))

In [20]:
df.head()

label                                               text  \
0  REAL  payal has accused filmmaker anurag kashyap of ...   
1  FAKE  a fourminutelong video of a woman criticising ...   
2  FAKE  republic poll a fake twitter account imitating...   
3  REAL  delhi teen finds place on un green list turns ...   
4  REAL  delhi a highlevel meeting underway at residenc...   

                                              Tokens  Len_token_stopwords  \
0  [payal, has, accused, filmmaker, anurag, kashy...                   97   
1  [a, fourminutelong, video, of, a, woman, criti...                  564   
2  [republic, poll, a, fake, twitter, account, im...                  464   
3  [delhi, teen, finds, place, on, un, green, lis...                  376   
4  [delhi, a, highlevel, meeting, underway, at, r...                  882   

                                 token_not_stopwords  Len_token_not_stopwords  \
0  [payal, accused, filmmaker, anurag, kashyap, b...                       51   
1  [fourminutelong, video, woman, criticising, go...                      302   
2  [republic, poll, fake, twitter, account, imita...                      275   
3  [delhi, teen, finds, place, un, green, list, t...                      236   
4  [delhi, highlevel, meeting, underway, residenc...                      518   

                                            stemming  \
0  [payal, accus, filmmak, anurag, kashyap, behav...   
1  [fourminutelong, video, woman, criticis, gover...   
2  [republ, poll, fake, twitter, account, imit, a...   
3  [delhi, teen, find, place, un, green, list, tu...   
4  [delhi, highlevel, meet, underway, resid, rajy...   

                                       lemmatization  \
0  [payal, accused, filmmaker, anurag, kashyap, b...   
1  [fourminutelong, video, woman, criticising, go...   
2  [republic, poll, fake, twitter, account, imita...   
3  [delhi, teen, find, place, un, green, list, tu...   
4  [delhi, highlevel, meeting, underway, residenc...   

                                  sent_lemmatization  
0  payal accused filmmaker anurag kashyap behavin...  
1  fourminutelong video woman criticising governm...  
2  republic poll fake twitter account imitating a...  
3  delhi teen find place un green list turn glass...  
4  delhi highlevel meeting underway residence raj...

# Bag Of Words(BOW)
## Binary Bag Of Words

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True)
bag = vectorizer.fit_transform(df['sent_lemmatization'])

In [22]:
print(vectorizer.get_feature_names_out())
print(bag.toarray())

['aa' 'aaa' 'aacharya' ... 'zvezda' 'zyada' 'zydus']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
vectorizer1 = CountVectorizer()
bag1 = vectorizer1.fit_transform(df['sent_lemmatization'])

In [24]:
print(vectorizer1.get_feature_names_out())
print(bag1.toarray())

['aa' 'aaa' 'aacharya' ... 'zvezda' 'zyada' 'zydus']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#TF-IDF

In [25]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['sent_lemmatization'])

In [26]:
print(vectorizer.get_feature_names_out())
print(X.toarray())

['aa' 'aaa' 'aacharya' ... 'zvezda' 'zyada' 'zydus']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
